### ISSUE TITLE
Passing amount never shows up in validCard fees

### ISSUE THREAD

**Issue by ecwyne** [fluidpay/fluidpay-tokenizer#25]
I've tried passing `amount` as string `"1.00"` and a number `100` in three different places and it's still not showing up in the `validCard` callback at all.

```js
new Tokenizer({
  apikey: "REDACTED",
  container: document.querySelector("#divTokenizer"),
  amount: '1.00',
  submission: (val) => console.log("submission", val),
  onPaymentChange: (val) => console.log("onPaymentChange", val),
  validCard: (val) => console.log("validCard", JSON.stringify(val, null, 2)),
  settings: {
    payment: {
      calculateFees: true,
      amount: '1.00',
    },
    amount: '1.00',
  },
});
```

I get the following in the `validCard` callback.

```js
{
  "isValid": true,
  "bin": {
    "bin": "411111",
    "card_brand": "VISA",
    "issuing_bank": "JPMORGAN CHASE BANK, N.A.",
    "card_type": "credit",
    "card_level_generic": "",
    "country": "USA",
    "is_surchargeable": true
  },
  "fees": {
    "service_fee": 0,
    "payment_adjustment": {
      "value": 0,
      "type": ""
    },
    "requested_amount": 0,
    "discount_amount": null, // this always returns null
    "surcharge": null // I need to know the surcharge amount
  }
}
```

**Comment by ecwyne** [comment]
The [docs](https://sandbox.fluidpay.com/docs/tokenizer/#methods) also mention a `.setBaseAmount(100)` method that does not exist.

**Comment by bvoelker** [comment]
Thank you so much for pointing some things out that are problematic on our side. Ill try to go through each one.

Just to make sure everything is setup. Make the merchant you are using has surcharge turned on and the processor you are using has the payment adjustment set.

We originally didnt pass in the amount to the fee calculations endpoint because the original purpose was to just identify flat surcharge values. But after reevaluation I added it in to be passed as a value to fee calculations in the event surcharge(payment adustment) was percentage based.

The amount return in the fees object is not in there because we felt as it it was not necessary due to the fact that you have the value to begin with so why return you a value you already know. That being said we will continue to make adjustments to that endpoint and possible in the future will return that value back. In the mean time reference the value you passed in.

I also added the ability to take in a processor id in the event you need to calculate fee based upon a processor id that isnt your default.

One thing to keep in mind about the calculate fees endpoint is it is a work in process right, so lets only rely on the surcharge value right now as i know that has been tested. Over the next few months we will fill that fees object with more and more amounts you can rely on.

Your right about the docs. I removed setBaseAmount from the docs considering it doesnt exist. Possibly old remains of previous iterations. I also added an example section for fee calculations.

I will be pushing these updates today so look out for them tomorrow to test with and let me know if everything worked out for you.

**Comment by ecwyne** [comment]
Thanks @bvoelker, will you let me know when I should expect this?

The merchant should now be set up with a 3% surcharge and I'm still receiving `null` for the surcharge in my testing.
